esphome:
  name: dotpwm
  friendly_name: DIY Purifier
  on_boot:
    priority: -100
    then:
      - delay: 3s
      - fan.turn_on:
          id: purifier_fan
          speed: 25

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:

ota:

wifi:
  ssid: "Archer C20"
  password: "ghanta@786"

  ap:
    ssid: "Dotpwm Fallback Hotspot"
    password: "Purifier@1001"

captive_portal:

web_server:
  port: 80

esp32_ble_server:

# ---------- PWM FAN ----------
output:
  - platform: ledc
    pin: GPIO25          # SAFE PWM PIN
    frequency: 25000 Hz
    id: fan_pwm

fan:
  - platform: speed
    output: fan_pwm
    name: "Purifier Fan"
    id: purifier_fan
    restore_mode: RESTORE_DEFAULT_OFF
    speed_count: 100

# ---------- RPM ----------
sensor:
  - platform: pulse_counter
    pin:
      number: GPIO27
      mode:
        input: true
    name: "Fan RPM"
    unit_of_measurement: "RPM"
    update_interval: 2s
    accuracy_decimals: 0
    count_mode:
      rising_edge: INCREMENT
      falling_edge: DISABLE
    filters:
      - multiply: 0.5
      - exponential_moving_average:
          alpha: 0.4

# ---------- PRESETS ----------
button:
  - platform: template
    name: "Quiet"
    on_press:
      - fan.turn_on:
          id: purifier_fan
          speed: 25

  - platform: template
    name: "Normal"
    on_press:
      - fan.turn_on:
          id: purifier_fan
          speed: 60

  - platform: template
    name: "Max"
    on_press:
      - fan.turn_on:
          id: purifier_fan
          speed: 100
