esphome:
  name: dotfan
  friendly_name: DIY Purifier

esp8266:
  board: nodemcuv2

logger:

api:

ota:

web_server:
  port: 80

wifi:
  ssid: "Archer C20"
  password: "ghanta@786"

  ap:
    ssid: "Dotfan Fallback Hotspot"
    password: "BrsC4t1zqGmM"

captive_portal:

# ---------------- PWM OUTPUT ----------------
output:
  - platform: esp8266_pwm
    pin: D1            # GPIO5
    frequency: 25000 Hz
    id: fan_pwm

# ---------------- FAN CONTROL ----------------
fan:
  - platform: speed
    output: fan_pwm
    name: "Purifier Fan"
    id: purifier_fan
    restore_mode: RESTORE_DEFAULT_ON

# ---------------- RPM (TACH) ----------------
sensor:
  - platform: pulse_counter
    pin:
      number: D2        # GPIO4
      mode:
        input: true
        pullup: true
    name: "Fan RPM"
    unit_of_measurement: "RPM"
    accuracy_decimals: 0
    update_interval: 2s
    filters:
      - multiply: 30    # 2 pulses per revolution

# ---------------- PRESET BUTTONS ----------------
button:
  - platform: template
    name: "Quiet"
    on_press:
      - fan.turn_on:
          id: purifier_fan
          speed: 25

  - platform: template
    name: "Normal"
    on_press:
      - fan.turn_on:
          id: purifier_fan
          speed: 60

  - platform: template
    name: "Max"
    on_press:
      - fan.turn_on:
          id: purifier_fan
          speed: 100
